<?php
/*
PHPDoctor: The PHP Documentation Creator
Copyright (C) 2004 Paul James <paul@peej.co.uk>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

/** The standard doclet. This doclet generates HTML output similar to that
 * produced by the Javadoc standard doclet.
 *
 * @package PHPDoctor.doclets.standard
 */
class standard {

	/** Our path to evaluate relative paths from.
	 *
	 * @var str
	 */
	var $_rootPath;

	/** The directory to place the generated files.
	 *
	 * @var str
	 */
	var $_d;

	/** Specifies the title to be placed in the HTML <title> tag.
	 *
	 * @var str
	 */
	var $_windowTitle = 'The Unknown Project';

	/** Specifies the title to be placed near the top of the overview summary
	 * file.
	 *
	 * @var str
	 */
	var $_docTitle = 'The Unknown Project';

	/** Specifies the header text to be placed at the top of each output file.
	 * The header will be placed to the right of the upper navigation bar.
	 *
	 * @var str
	 */
	var $_header = 'Unknown';

	/** Specifies the footer text to be placed at the bottom of each output file.
	 * The footer will be placed to the right of the lower navigation bar.
	 *
	 * @var str
	 */
	var $_footer = 'Unknown';

	/** Specifies the text to be placed at the bottom of each output file. The
	 * text will be placed at the bottom of the page, below the lower navigation
	 * bar.
	 *
	 * @var str
	 */
	var $_bottom = 'This document was generated by <a href="http://phpdoctor.sourceforge.net/">PHPDoctor: The PHP Documentation Creator</a>';

	/** Create a class tree?
	 *
	 * @var str
	 */
	var $_tree = TRUE;

	/** Doclet constructor.
	 *
	 * @param rootDoc rootDoc
	 */
	function standard(&$rootDoc) {
	
		// set doclet options
		$phpdoctor =& $rootDoc->phpdoctor();
		$options =& $rootDoc->options();
		
		$this->_rootPath = $phpdoctor->_sourcePath;

		if (isset($options['d'])) {
			$this->_d = $phpdoctor->makeAbsolutePath($options['d'], $phpdoctor->_sourcePath);
		} elseif (isset($options['output_dir'])) {
			$this->_d = $phpdoctor->makeAbsolutePath($options['output_dir'], $phpdoctor->_sourcePath);
		} else {
			$this->_d = $phpdoctor->makeAbsolutePath('apidocs', $phpdoctor->_sourcePath);
		}
		$this->_d = $phpdoctor->fixPath($this->_d);
		
		if (isset($options['windowtitle'])) $this->_windowTitle = $options['windowtitle'];
		if (isset($options['doctitle'])) $this->_docTitle = $options['doctitle'];
		if (isset($options['header'])) $this->_header = $options['header'];
		if (isset($options['footer'])) $this->_footer = $options['footer'];
		if (isset($options['bottom'])) $this->_bottom = $options['bottom'];

		if (isset($options['tree'])) $this->_tree = $options['tree'];
		
		var_dump($this);
		
		echo "Done\n";
	
	}
	
}
?>